### ISSUE TITLE
Cannot install sb admin 2 extension to visual studio 2015

### ISSUE THREAD

**Issue by JobayerAhmmed** [BlackrockDigital/startbootstrap-sb-admin-2#154]
I downloaded sb admin 2 from [visualstudiogallery](https://visualstudiogallery.msdn.microsoft.com/f460cb77-92fa-426b-96e7-ebc285a317aa). When I go to install this in visual studio 2015 community, it shows error - **This extension is not installable on any currently installed products.** Here is the error log - 

```
10/13/2016 7:16:27 PM - Microsoft VSIX Installer
10/13/2016 7:16:27 PM - -------------------------------------------
10/13/2016 7:16:27 PM - Initializing Install...
10/13/2016 7:16:27 PM - Extension Details...
10/13/2016 7:16:27 PM -     Identifier         : sb_admin_2.Template..450c50a5-1b04-424b-8090-2353169886fc
10/13/2016 7:16:27 PM -     Name               : ASP MVC 5 with sb admin 2 bootstrap template
10/13/2016 7:16:27 PM -     Author             : Luis Vasquez
10/13/2016 7:16:27 PM -     Version            : 1.0
10/13/2016 7:16:27 PM -     Description        : Default ASP MVC 5 project with sb admin 2 bootstrap theme

10/13/2016 7:16:27 PM -     Locale             : en-US
10/13/2016 7:16:27 PM -     MoreInfoURL        : http://lvasquez.github.io/2015/07/19/sb-admin-2-bootstrap-template-asp-mvc/
10/13/2016 7:16:27 PM -     InstalledByMSI     : False
10/13/2016 7:16:27 PM -     SupportedFrameworkVersionRange : [4.5,)
10/13/2016 7:16:27 PM - 
10/13/2016 7:16:27 PM -     SignatureState     : Unsigned
10/13/2016 7:16:27 PM -     Supported Products : 
10/13/2016 7:16:27 PM -         Microsoft.VisualStudio.Ultimate
10/13/2016 7:16:27 PM -             Version : [12.0,13.0)
10/13/2016 7:16:27 PM -         Microsoft.VisualStudio.Pro
10/13/2016 7:16:27 PM -             Version : [12.0,13.0)
10/13/2016 7:16:27 PM -         Microsoft.VisualStudio.Premium
10/13/2016 7:16:27 PM -             Version : [12.0,13.0)
10/13/2016 7:16:27 PM -         Microsoft.VisualStudio.VWDExpress
10/13/2016 7:16:27 PM -             Version : [12.0,13.0)
10/13/2016 7:16:27 PM - 
10/13/2016 7:16:27 PM -     References         : 
10/13/2016 7:16:27 PM - Signature Details...
10/13/2016 7:16:27 PM -     Extension is not signed.
10/13/2016 7:16:27 PM - 
10/13/2016 7:16:27 PM - Searching for applicable products...
10/13/2016 7:16:27 PM - Found installed product - Microsoft Visual Studio Community 2015
10/13/2016 7:16:27 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
10/13/2016 7:16:27 PM - Found installed product - Global Location
10/13/2016 7:16:27 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

How can I solve this? Thanks in advance.

**Comment by jantman** [comment]
I don't believe that Visual Studio thing is directly related to this project. The output above includes a "More Info URL" of http://lvasquez.github.io/2015/07/19/sb-admin-2-bootstrap-template-asp-mvc/ perhaps you should contact that person.
