### ISSUE TITLE
Cannot run npm install

### ISSUE THREAD

**Issue by chirrindul** [BlackrockDigital/startbootstrap-sb-admin-2#470]
I've performed these actions:
1. Download from browser "https://github.com/StartBootstrap/startbootstrap-sb-admin-2/archive/gh-pages.zip" but lastly it downloads the file:
`6631182 feb  8 22:05 startbootstrap-sb-admin-2-gh-pages.zip`
2. Extract the contents to new folder 
`~/ExpressProjects/startbootstrap-sb-admin-2-gh-pages`
3. run npm install. Then there is the following error:

```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code 1
npm ERR! path /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/lib/nodejs/node-v20.11.0-linux-x64/bin/node /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/lib/nodejs/node-v20.11.0-linux-x64/bin/node',
npm ERR! gyp verb cli   '/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.11.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 20.11.0
npm ERR! gyp verb command install [ '20.11.0' ]
npm ERR! gyp verb install input version string "20.11.0"
npm ERR! gyp verb install installing version: 20.11.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 20.11.0
npm ERR! gyp verb build dir attempting to create "build" dir: /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/angel/.node-gyp/20.11.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/angel/.node-gyp/20.11.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/angel/.node-gyp/20.11.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
npm ERR!     params['parallel'], params['root_targets'])
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
npm ERR!     variables, includes, depth, check, True)
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
npm ERR!     includes, True, check)
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
npm ERR!     aux_data, includes, check)
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
npm ERR!     LoadOneBuildFile(include, data, aux_data, None, False, check),
npm ERR!   File "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
npm ERR!     None)
npm ERR!   File "/home/angel/.node-gyp/20.11.0/include/node/common.gypi", line 1
npm ERR!     incremental linking
npm ERR!                       ^
npm ERR! SyntaxError: invalid syntax
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Linux 6.5.0-15-generic
npm ERR! gyp ERR! command "/usr/local/lib/nodejs/node-v20.11.0-linux-x64/bin/node" "/home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/angel/ExpressProjects/startbootstrap-sb-admin-2-gh-pages/node_modules/node-sass
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

**Comment by ccccgw** [comment]
您好，您的邮件我已经收到，我会尽快回复！  谢谢！

**Comment by Limoneto** [comment]
try with npm i --force

**Comment by hashaam1217** [comment]
I'm having the exact same problem

**Comment by ericsizemore** [comment]
I am assuming you are wanting to install the theme itself, right? If so, the issue you are having is because you are not downloading the correct archive. 'gh-pages' is used by github to host pages/docs for a repository. You want https://github.com/StartBootstrap/startbootstrap-sb-admin-2/archive/refs/heads/master.zip

**Comment by ccccgw** [comment]
您好，您的邮件我已经收到，我会尽快回复！  谢谢！

**Comment by INF0303** [comment]
Getting same  **gyp** issue.

**Comment by ccccgw** [comment]
您好，您的邮件我已经收到，我会尽快回复！  谢谢！
